name: deploy-orders

on:
  push:
    branches: 
      - master
    paths:
      - 'orders/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout master
      uses: actions/checkout@v2

    - name: Build container image
      run: cd orders && docker build -t andreyohiienko/orders .

    - name: Sign in to Docker account
      run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push image to DigitalOcean Container Registry
      run: docker push andreyohiienko/orders

    - name: Install doctl
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

    - name: Save DigitalOcean kubeconfig
      run: doctl kubernetes cluster kubeconfig save ticketing

    - name: Verify deployment
      run: kubectl rollout restart deployment orders-depl